services:
  mongodb:
    image: mongo:7.0
    container_name: urbantransit_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    environment:
      MONGO_INITDB_DATABASE: urbantransit_iq

volumes:
  mongodata:
    driver: local
