from pymongo import MongoClient
import random
import datetime

client = MongoClient('mongodb://localhost:27017/')
db = client['urbantransit_iq']

# Delete the randomly generated records (they have no proper correlations)
# The original 1M records were generated by the proper data_generator which has correlations
# My new 1M records broke the model because is_delayed was random

# Count records that have realistic correlations vs random ones
# The original records were inserted before our expansion - they have a proper timestamp format
# The new records have timestamps from 2025. Let's delete those.
deleted = db.passenger_counts.delete_many({"timestamp": {"$gte": datetime.datetime(2025, 1, 1), "$lt": datetime.datetime(2026, 1, 1)}})
print(f"Deleted {deleted.deleted_count} poorly generated records")

current = db.passenger_counts.count_documents({})
print(f"Current count after cleanup: {current}")

# Now regenerate 1M records WITH PROPER feature-target correlations
target_total = 2000000
needed = target_total - current
if needed <= 0:
    print("Already at 2M, no generation needed")
    exit()

print(f"Generating {needed} records with proper ML correlations...")

routes = db.passenger_counts.distinct("route_id")
if not routes:
    routes = [f"R-{str(i).zfill(3)}" for i in range(1, 51)]

batch_size = 50000
inserted = 0

while inserted < needed:
    batch = []
    chunk = min(batch_size, needed - inserted)
    for _ in range(chunk):
        hour = random.randint(0, 23)
        
        # Peak hours have higher boarding/load (realistic correlation)
        is_peak = hour in [7, 8, 9, 17, 18, 19]
        is_late_night = hour in [0, 1, 2, 3, 4, 22, 23]
        
        if is_peak:
            boarding = random.randint(15, 45)
            alighting = random.randint(10, 35)
            load = random.randint(40, 85)
        elif is_late_night:
            boarding = random.randint(0, 8)
            alighting = random.randint(0, 6)
            load = random.randint(0, 15)
        else:
            boarding = random.randint(3, 25)
            alighting = random.randint(2, 20)
            load = random.randint(10, 50)
        
        # REALISTIC delay correlation:
        # High load + peak hour = MORE likely delayed
        # Low load + off-peak = LESS likely delayed
        delay_score = 0
        if load > 60: delay_score += 3
        elif load > 40: delay_score += 1
        if is_peak: delay_score += 2
        if boarding > 25: delay_score += 1
        
        # Convert score to probability
        delay_prob = min(0.95, max(0.05, delay_score / 7.0))
        is_delayed = 1 if random.random() < delay_prob else 0
        
        route = random.choice(routes)
        month = random.randint(1, 12)
        day = random.randint(1, 28)
        
        ts = datetime.datetime(2026, month, day, hour, random.randint(0, 59))
        
        batch.append({
            "route_id": route,
            "boarding": boarding,
            "alighting": alighting,
            "load": load,
            "hour": hour,
            "is_delayed": is_delayed,
            "timestamp": ts,
        })
    
    db.passenger_counts.insert_many(batch)
    inserted += chunk
    print(f"Inserted {inserted}/{needed}")

final = db.passenger_counts.count_documents({})
print(f"Final passenger_counts: {final}")
